In [11]:
#1
from numpy import * #import  numpy
from matplotlib import pyplot as p #import matplotlib
from scipy import stats #scipy library
import pandas as pd #import pandas
from numpy.random import randn
from numpy.random import seed
from scipy.stats import pearsonr,zscore
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


In [ ]:
#2 Create a matrix

A = array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3 Trace of a matrix
A = array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(A)
B = array([[1, 2, 3], [4, 5, 6],[1,2,3]])
print(B)
print('Trace',trace(A))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [1 2 3]]
Trace 15


In [ ]:
#4 Arithmetic operations on a matrix
C = A + B
print('Sum\n',C) #add matrix
C=A-B 
print('Difference\n',C) #subtract matrix
C= A*B
print('Product\n',C) #multiply matrix
C=dot(A,B)
print('Dot Product\n',C)
C= A/B 
print('Division',C) #divide matrix

In [ ]:
'''Can we perform addition, multiplication and division on
X=[[3, 6, 9], [5, -10, 15], [-7, 14, 21]]
Y=[[9, -18, 27], [11, 22, 33], [13, -26, 39]]'''


[[ 12 -12  36]
 [ 16  12  48]
 [  6 -12  60]]
[[ -6  24 -18]
 [ -6 -32 -18]
 [-20  40 -18]]
[[ 210 -156  630]
 [ 130 -700  390]
 [ 364 -112 1092]]
[[ 0.33333333 -0.33333333  0.33333333]
 [ 0.45454545 -0.45454545  0.45454545]
 [-0.53846154 -0.53846154  0.53846154]]


In [ ]:
#5 Transpose of a matrix
a=array([[3,6,9],[1,2,3],[4,5,6]])
print(transpose(a))

In [ ]:
#6 Determinant of a matrix
n = array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
det = linalg.det(n)
print("\nDeterminant of given 3X3 square matrix:")
print(int(det))

In [ ]:
#7 Inverse of a matrix
total=array([118.4,135.2])
fare=array([[3,3.5],[3.2,3.6]])
fareinverse=linalg.inv(fare)
print("Total fare",dot(total,fareinverse))

In [ ]:
#8 Vectors in python

v1=array([1,2,10,5])
v2=array([4,6,1,5])
print("Sum ",v1+v2)
print('Difference',v1-v2)
print('Product',v1*v2)
print('Dot product',dot(v1,v2))
print(p.plot(v1))
print(p.plot(v2))

In [ ]:
#9 Data Science

x=array([25,95,18,20,23,90,92,23,21,24])
print('Mean',mean(x))
print('Median',median(x))
print('Mode',stats.mode(x))
print('Variance',var(x))
print('Standard Deviation',std(x))

In [ ]:
#10 Frequency table
df = pd.DataFrame({'Grade': ['A','A','A','B','B', 'B', 'B', 'C', 'D', 'D'],
                   'Age': [18, 18, 18, 19, 19, 20, 18, 18, 19, 19],
                   'Gender': ['M','M', 'F', 'F', 'F', 'M', 'M', 'F', 'M', 'F']})
pd.crosstab(index=df['Grade'], columns='count')

The way to interpret this is as follows:

3 students received an ‘A’ in the class.
4 students received a ‘B’ in the class.
1 student received a ‘C’ in the class.
2 students received a ‘D’ in the class.

In [ ]:
#11 Line graph
df = pd.DataFrame({"Year" : [2014,2015,2016,2017,2018], 
                  "Sales" : [2000, 3000, 4000, 3500, 6000]})
p.plot(df["Year"], df["Sales"])
p.title("Simple Line Plot")
p.xlabel('Year')
p.ylabel('Sales')

In [ ]:
#12 bar graph using matplotlib
import matplotlib.pyplot as plt
data1 = [23,85, 72, 43, 52]
data2 = [42, 35, 21, 16, 9]
plt.bar(range(len(data1)), data1)
plt.bar(range(len(data2)), data2, bottom=data1)
plt.show()

In [ ]:
#13 bar graph using matplotlib 
data = {'C':20, 'C++':15, 'Java':30,
        'Python':35}
courses = list(data.keys())
values = list(data.values())
fig = plt.figure(figsize = (10, 5))
# creating the bar plot
plt.bar(courses, values, color ='maroon',
     width = 0.4)
plt.xlabel("Courses offered")
plt.ylabel("No. of students enrolled")
plt.title("Students enrolled in different courses")
plt.show()

In [ ]:
#14 Pie chart
fig = p.figure()
ax = fig.add_axes([0,0,1,1])
ax.axis('equal')
langs = ['C', 'C++', 'Java', 'Python', 'PHP']
students = [23,17,35,29,12]
ax.pie(students, labels = langs,autopct='%1.2f%%')
p.show()

In [ ]:
#15 Scatterplot

raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'], 
        'female': [0, 1, 1, 0, 1],
        'age': [42, 52, 36, 24, 73], 
        'preTestScore': [4, 24, 31, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'female', 'preTestScore', 'postTestScore'])
plt.scatter(df.preTestScore, df.postTestScore, s=df.age)

In [ ]:
#16 Histogram
x = random.randn(1000)  
plt.hist(x)  
plt.xlabel('Intervals')  
plt.ylabel('Value')  
plt.title('Distribution of the variable x')  
plt.show()  


In [ ]:
#17 Z-Score
data = array([6, 7, 7, 12, 13, 13, 15, 16, 19, 22])
print(zscore(data))

In [ ]:
#18 Covariance, Pearson Coefficient

seed(1)
# prepare data
data1 = 20 * randn(1000) + 100
data2 = data1 + (10 * randn(1000) + 50)
# summarize
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1))) #Mean and standard deviation of X
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2))) #Mean and standard deviation of Y
# plot
p.scatter(data1, data2)
p.show()
covariance = cov(data1, data2) #Numpy method cov
print(covariance)
corr, _ = pearsonr(data1, data2)
print('Pearsons correlation: %.3f' % corr) #Pearson coefficient


In [ ]:
#19 Least Square Method for best fit
x = array([2,3,5,7,9])
y=array([4,5,7,10,15])
b=size(x)
mean_x=mean(x)
mean_y=mean(y)
a1=sum(y*x)-b*mean_x*mean_y
a2=sum(x*x)-b*mean_x*mean_y
m=a1/a2
c=mean_y-m*mean_x
p.scatter(x,y,marker="o",s=30)
y_pred=m*8+c
p.scatter(8,y_pred, marker="o",color='g')
p.show()


In [ ]:
#20 Confusion Matrix

# actual values
actual = [1,0,0,1,0,0,1,0,0,1]
# predicted values
predicted = [1,0,0,1,0,0,0,1,0,0]

# confusion matrix
matrix = confusion_matrix(actual,predicted, labels=[1,0])
print('Confusion matrix : \n',matrix)

# outcome values order in sklearn
tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1)
print('Outcome values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n',matrix)